# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{smsonrails}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Blythe Dunham"]
  s.date = %q{2010-01-01}
  s.description = %q{Sms on Rails provides your app with instant SMS integration}
  s.email = %q{blythe@snowgiraffe.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "Manifest",
     "README.rdoc",
     "Rakefile",
     "app/controllers/admin/sms_on_rails/base_controller.rb",
     "app/controllers/admin/sms_on_rails/drafts_controller.rb",
     "app/controllers/admin/sms_on_rails/outbounds_controller.rb",
     "app/controllers/admin/sms_on_rails/phone_carriers_controller.rb",
     "app/controllers/admin/sms_on_rails/phone_numbers_controller.rb",
     "app/controllers/sms_on_rails/creation_support.rb",
     "app/controllers/sms_on_rails_controller.rb",
     "app/helpers/admin/sms_on_rails/drafts_helper.rb",
     "app/helpers/admin/sms_on_rails/phone_carriers_helper.rb",
     "app/helpers/sms_on_rails/phone_numbers_helper.rb",
     "app/helpers/sms_on_rails/sms_helper.rb",
     "app/models/sms_on_rails/draft.rb",
     "app/models/sms_on_rails/outbound.rb",
     "app/models/sms_on_rails/phone_carrier.rb",
     "app/models/sms_on_rails/phone_number.rb",
     "app/views/admin/sms_on_rails/base/index.html.erb",
     "app/views/admin/sms_on_rails/drafts/_show.html.erb",
     "app/views/admin/sms_on_rails/drafts/edit.html.erb",
     "app/views/admin/sms_on_rails/drafts/index.html.erb",
     "app/views/admin/sms_on_rails/drafts/new.html.erb",
     "app/views/admin/sms_on_rails/drafts/send_sms.html.erb",
     "app/views/admin/sms_on_rails/drafts/show.html.erb",
     "app/views/admin/sms_on_rails/outbounds/edit.html.erb",
     "app/views/admin/sms_on_rails/outbounds/index.html.erb",
     "app/views/admin/sms_on_rails/outbounds/new.html.erb",
     "app/views/admin/sms_on_rails/outbounds/show.html.erb",
     "app/views/admin/sms_on_rails/phone_carriers/edit.html.erb",
     "app/views/admin/sms_on_rails/phone_carriers/index.html.erb",
     "app/views/admin/sms_on_rails/phone_carriers/new.html.erb",
     "app/views/admin/sms_on_rails/phone_carriers/show.html.erb",
     "app/views/admin/sms_on_rails/phone_numbers/edit.html.erb",
     "app/views/admin/sms_on_rails/phone_numbers/index.html.erb",
     "app/views/admin/sms_on_rails/phone_numbers/new.html.erb",
     "app/views/admin/sms_on_rails/phone_numbers/show.html.erb",
     "app/views/layouts/sms_on_rails/basic.html.erb",
     "app/views/sms_on_rails/_phone_carrier_form_item.html.erb",
     "app/views/sms_on_rails/_send_sms.html.erb",
     "app/views/sms_on_rails/index.html.erb",
     "app/views/sms_on_rails/send_sms.html.erb",
     "app/views/sms_on_rails/show.html.erb",
     "config/routes.rb",
     "db/data/fixtures/sms_phone_carriers.yml",
     "db/migrate/sms_on_rails_carrier_tables.rb",
     "db/migrate/sms_on_rails_model_tables.rb",
     "db/migrate/sms_on_rails_phone_number_tables.rb",
     "db/seed_data.rb",
     "generators/sms_on_rails/USAGE",
     "generators/sms_on_rails/commands/inserts.rb",
     "generators/sms_on_rails/commands/timestamps.rb",
     "generators/sms_on_rails/runners/add_all_models.rb",
     "generators/sms_on_rails/runners/dependencies.rb",
     "generators/sms_on_rails/runners/remove_all_models.rb",
     "generators/sms_on_rails/runners/sms_on_rails_routes.rb",
     "generators/sms_on_rails/sms_on_rails_generator.rb",
     "generators/sms_on_rails/templates/configuration/clickatell.rb",
     "generators/sms_on_rails/templates/configuration/email_gateway.rb",
     "generators/sms_on_rails/templates/migrate/schema_migration.rb",
     "generators/sms_on_rails/templates/migrate/sms_on_rails_update_phone_numbers.rb",
     "generators/sms_on_rails/templates/phone_number_collision.rb",
     "init.rb",
     "install.rb",
     "lib/sms_on_rails.rb",
     "lib/sms_on_rails/activerecord_extensions/acts_as_deliverable.rb",
     "lib/sms_on_rails/activerecord_extensions/acts_as_substitutable.rb",
     "lib/sms_on_rails/activerecord_extensions/has_a_sms_service_provider.rb",
     "lib/sms_on_rails/activerecord_extensions/lockable_record.rb",
     "lib/sms_on_rails/all_models.rb",
     "lib/sms_on_rails/model_support/draft.rb",
     "lib/sms_on_rails/model_support/outbound.rb",
     "lib/sms_on_rails/model_support/phone_carrier.rb",
     "lib/sms_on_rails/model_support/phone_number.rb",
     "lib/sms_on_rails/model_support/phone_number_associations.rb",
     "lib/sms_on_rails/schema_helper.rb",
     "lib/sms_on_rails/service_providers/base.rb",
     "lib/sms_on_rails/service_providers/clickatell.rb",
     "lib/sms_on_rails/service_providers/dummy.rb",
     "lib/sms_on_rails/service_providers/email_gateway.rb",
     "lib/sms_on_rails/service_providers/email_gateway_support/errors.rb",
     "lib/sms_on_rails/service_providers/email_gateway_support/sms_mailer.rb",
     "lib/sms_on_rails/service_providers/email_gateway_support/sms_mailer/sms_through_gateway.erb",
     "lib/sms_on_rails/util/sms_error.rb",
     "lib/smsonrails.rb",
     "public/images/sms_on_rails/railsYoDawg.jpg",
     "public/stylesheets/sms_on_rails.css",
     "tasks/sms_on_rails_tasks.rake",
     "test/active_record_extensions/delivery_and_locking_test.rb",
     "test/models/draft_test.rb",
     "test/models/outbound_test.rb",
     "test/models/phone_number_test.rb",
     "test/run.rb",
     "test/service_providers/abstract_test_support.rb",
     "test/service_providers/clickatell_test.rb",
     "test/service_providers/email_gateway_test.rb",
     "test/test_helper.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/blythedunham/smsonrails}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Sms on Rails provides your app with instant SMS integration}
  s.test_files = [
    "test/active_record_extensions/delivery_and_locking_test.rb",
     "test/models/draft_test.rb",
     "test/models/outbound_test.rb",
     "test/models/phone_number_test.rb",
     "test/run.rb",
     "test/service_providers/abstract_test_support.rb",
     "test/service_providers/clickatell_test.rb",
     "test/service_providers/email_gateway_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_development_dependency(%q<clickatell>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.0.0"])
      s.add_runtime_dependency(%q<static_record_cache>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<clickatell>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 2.0.0"])
      s.add_dependency(%q<static_record_cache>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<clickatell>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 2.0.0"])
    s.add_dependency(%q<static_record_cache>, [">= 0"])
  end
end

